### ISSUE TITLE
The plan for September

### ISSUE THREAD

**Issue by agstephens** [roocs/rook#36]
!NOTE: This issue is just for building a plan, not for doing the work!

**Milestones:**
 - M1: 28th Aug
 - M2: 4th Sept
 - M3: 11th Sept
 - M4: 18th Sept - show and tell day

**Primary objectives:**
 - [x] Deployed cluster at CEDA [M2]
 - [x] Create system for automating releases [M1]
   - script the update process - from some common metadata - put history in `roocs-utils` 
     - put them on PyPI and GitHub
   - Fix issue with `setup.py` and `requirements.txt` when pointing to github repos.
   - Then `rook` playbook will respect the releases listed.
   - Playbook will: update `rook` from github, then re-run conda and pip installs.
 - [x] Open to requests from CDS and DKRZ [M3]
   - firewall settings
   - need to write service docs 
   - Liaise with SCD to check service
 - [X] Example usage in rooki documentation/notebooks [M3]
   - write some more docs

**Secondary objectives:**
 - [X] Repository for batch testing `daops.subset`, checking and logging of results [M2]
 - [x] Monitoring system: GeoHealthCheck - for service uptime monitoring [M3]
   - DRKZ to set up a new VM for this
 - [x] Production service C/I: example notebooks in `rooki` (with real IPs?): [M4]
   - _could_ use PAVICS system
   - or through `pytest` (extension for notebooks)
   - via cron or running on Travis C/I
 - [x] Scalable solution for chunking data out of and into NetCDF [M3]

Tertiary objectives:
 - [x] Deployment at DKRZ, with Load-balanced front-end (Route55)
 - [x] Load-test with python locust?

**Comment by agstephens** [comment]
Note, both of these formats seem to work in pip `requirements.txt` file:

```
roocs_utils @ git+https://github.com/roocs/roocs-utils.git
git+https://github.com/roocs/roocs-utils.git#roocs_utils
```
